FROM node:20-alpine AS builder
WORKDIR /build
COPY web-application/client/package*.json ./
RUN npm ci
COPY web-application/client/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /build/dist/ /usr/share/nginx/html/
COPY mlops/docker/nginx.conf /etc/nginx/conf.d/default.conf
RUN adduser -D -H -s /sbin/nologin nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
